/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#643f00",
        "secondary-fixed-dim": "#88d982",
        "secondary": "#1b6d24",
        "background": "#f7fafc",
        "tertiary-fixed": "#ffddb5",
        "secondary-container": "#a0f399",
        "tertiary-container": "#774e0b",
        "on-background": "#181c1e",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface": "#f7fafc",
        "inverse-on-surface": "#eef1f3",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#94cdf4",
        "on-tertiary-container": "#fbc277",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-tint": "#256486",
        "outline-variant": "#c0c7ce",
        "tertiary": "#5a3800",
        "surface-container-high": "#e5e9eb",
        "primary": "#004461",
        "on-tertiary-fixed": "#2a1800",
        "on-secondary-fixed-variant": "#005312",
        "on-secondary-container": "#217128",
        "on-primary-container": "#9ad3fa",
        "error": "#ba1a1a",
        "surface-container-low": "#f1f4f6",
        "secondary-fixed": "#a3f69c",
        "outline": "#71787e",
        "on-secondary-fixed": "#002204",
        "surface-container": "#ebeef0",
        "on-tertiary": "#ffffff",
        "on-surface": "#181c1e",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d7dadc",
        "error-container": "#ffdad6",
        "on-surface-variant": "#41484d",
        "on-primary-fixed-variant": "#004c6c",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#f5bc71",
        "inverse-primary": "#94cdf4",
        "primary-container": "#1a5c7e",
        "on-primary-fixed": "#001e2e",
        "surface-bright": "#f7fafc",
        "primary-fixed": "#c7e7ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
